python3 transcribe_and_align.py --video 120gOWa2Jl0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video RE4RWUbmVz4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video GFbPi4VGHeE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video -emyoH9dkrY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video eofOvnBu2p0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video kn9tCPtaECs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video OSsme2f8kis --manifest verification_manifest.csv
python3 transcribe_and_align.py --video gomHXskSVYk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ZBiiHwo1nOk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video OkT4exIMvkE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video PIqCuNGQdx8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video _YNaTMx17_k --manifest verification_manifest.csv
python3 transcribe_and_align.py --video HG7Qh-LYQ18 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Uytjm-LUrE0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video sqyhfeKv6u8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video CGEbQ8uogUs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video XFrCJEgmBIE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video N20BB1dUMO0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video fWA6v36nNHQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video EHa20LQrETE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Co6LSEXaYH0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video yn8MB5JR08Y --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Wo-pqTcM11U --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 9FFIBlZjGXU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video A76ltMHyYow --manifest verification_manifest.csv
python3 transcribe_and_align.py --video pa_nMbEn80k --manifest verification_manifest.csv
python3 transcribe_and_align.py --video BaXlx5UI4_8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video MaT-mCu88Dg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video maO9FgPtnGY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video HdqXrmtisBY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ZJOU-iUAS0g --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 9Am_EoeCeWI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video E5nf8yP0LXU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video iSvV7ePdxlE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 4wGZACqA1SA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video kDZO_-G59yk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video jaOAcJrypQU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 4YS7FNaHVqs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video RJPiZ7XBPX8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video HDiuQDpkatM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Ig3cpc-N1Rg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video UlmXLDv0mTE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video tNIccz0L-WQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video CkCBPjTiDnI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video YcZdMUIY49M --manifest verification_manifest.csv
python3 transcribe_and_align.py --video IuZ30vZcQlc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video uKkFdc17EUs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video pNxKBWdRNsk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video w1Fi43t3eVE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video PjWPL8gfUkQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ebY25eDL6ng --manifest verification_manifest.csv
python3 transcribe_and_align.py --video E9uwgUwqEvM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video WGy4kZ4j0J8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video lpyA8U9bbu0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video nFh-8glkLLs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ckKaTwr_l88 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video IQ2_t0-5Y9w --manifest verification_manifest.csv
python3 transcribe_and_align.py --video RurmvYKtV5E --manifest verification_manifest.csv
python3 transcribe_and_align.py --video SH9gnaGwmqM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 6S1vG_IWttI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video KUsMaTuCcgw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video GnlR0yY6hCg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video oWmGZZHT4yY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hwRsxTtfiYk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video WuJPb8Lzs0I --manifest verification_manifest.csv
python3 transcribe_and_align.py --video kYIdjOLQUgM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Va-lDaoNuNs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video zpFz68Avc1Q --manifest verification_manifest.csv
python3 transcribe_and_align.py --video IpCepWmcsdg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video HpDeBZsI2wU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hrylfu_1j1U --manifest verification_manifest.csv
python3 transcribe_and_align.py --video itd__xT3qks --manifest verification_manifest.csv
python3 transcribe_and_align.py --video wIlhEJZv-YM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video scPR_sUK1qI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ftnPAHIkZGc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video KxUj9pS59U8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video bIggVrqJbs8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video m13PmvXmUPc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 9xo8X8a5sqk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ZDV3gRxB4wY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video H-Z5yHulmQ0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video zAm_CqkuERk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video YC9tYbtPIV4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 2UUy7bVVdD4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video X1iM8Q6a0fE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video _OD9I09c5rY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video mT2efMLR108 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ijeipsfxf7Q --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DmCQxaCzTEU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 1RYAdjo0Eds --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Vi5nsipXNGY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Zkz3G5MmrMw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video T5IgNZih1HI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video pm5cfku-BTc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video cN_xVVlB0tE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video kdDHme1JH-c --manifest verification_manifest.csv
python3 transcribe_and_align.py --video JbMwaIVjBuU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video E3uq0jlv4LQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video taeEC2-THx0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video TehiqdHO83Q --manifest verification_manifest.csv
python3 transcribe_and_align.py --video wH8R4NvZutg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video AUmPYzfD_Vw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video YrSXjhMWh-8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video fsM1xOJlEA4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video FI0gwMnAhS4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 31hAgkxq3is --manifest verification_manifest.csv
python3 transcribe_and_align.py --video iSLVW1f6FG0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video fsVpmOa4xSM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video nkBX7Mi9__U --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 2IP-H-AxWo4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video pAC0UQ_cvZM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video c2X7vUh9YAQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video scZ1g_esFRk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video SYjBVSespC4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Kj3ADbi7vC4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video vmG-cGEQG3A --manifest verification_manifest.csv
python3 transcribe_and_align.py --video H6GLiLITu0s --manifest verification_manifest.csv
python3 transcribe_and_align.py --video p2ntNIZE3UE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video -GBsqf6qNeQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Fx0UQufuJws --manifest verification_manifest.csv
python3 transcribe_and_align.py --video dSWcRSUHHuo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video fqdHUGBS0w8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video SI287irobqw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Zav45PqHwww --manifest verification_manifest.csv
python3 transcribe_and_align.py --video kHx-Uh1JwKc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video TgcOxHjo_Ws --manifest verification_manifest.csv
python3 transcribe_and_align.py --video bloBlOY2Lx0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video SBY8sy1K7bE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video d99u78ULW3E --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hGYZz-HM4dw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Efeb29uwnkA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video LkDN45sZhg0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video BfizQ4Tc0BY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 0JAMiyWefnc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video jwDiHf4oWaI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video M7kB-ZPmwBs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video EPdMB3hnzM4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 48EI5ya08wg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video gX4ARBEJ0tc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Cay6O4ppyiM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video LJD4T70uetI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video k_PgWPCoudQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video zHZRxz3NMSc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ZG6nmNtjexo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 91exdzUJG0c --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DdiBkBHSAyc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video OyD-ke982tk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DnkeVms0AaM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video HvonAqZFsY8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ZHectEX30mc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video AiJmC4Vko5I --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Q4YgLsT2l5M --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hw-SJLIsSx4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Vl_55AizHSc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 8rlJe-YYLqs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hpUYmGH2aAA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Z0myWg2FjrA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 7n9ZRH8xXE4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 0quD4648pEg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ghE2NCcfbLw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 58LimvT99OU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 1HKpNbsF6S4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video dUWQvf7KxZM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video thiLiuCnIB0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video FjS7FSOkjw4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video fX-wa3Pg_8s --manifest verification_manifest.csv
python3 transcribe_and_align.py --video XkwP60KKoaw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video YkaIOY7xUCM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ELyyrKfP4ug --manifest verification_manifest.csv
python3 transcribe_and_align.py --video d07BPy9Uqm4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video T5AtXiL_VVc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video zV7n4wIMLRs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 6vwg2ghf_rI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ANLyJhlGmgw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video s-HOWLvvSMo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 0vqdc3SCPWU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video WgvVzsPUplc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video f8vXLTIj7j4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 1m_QgDVSyx0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video SMqTroX6IlI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Y6nkRBEv71E --manifest verification_manifest.csv
python3 transcribe_and_align.py --video GJ_UodeCLRQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video GwJgjhp17bg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DxAOsnvSWlg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video bwsyrDN-lns --manifest verification_manifest.csv
python3 transcribe_and_align.py --video MuaXms6stW4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video O8_MOhk6NT8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 2FvUi5xPDTA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 0rS9_QHUHbo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video KAwZg_y7_wg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ka8JY05XaMM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 4Yho2i88AZw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Zq-FhmcZqEI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video nnGD8mJfpp8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video u0b4iZpSlKo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 2U4hmx75M3A --manifest verification_manifest.csv
python3 transcribe_and_align.py --video PqDxaC0CLWc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DPYveTNndyw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ER4NYxLXq20 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video W9AMAi3LfCQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video j1fShuyoDBw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 2YFXGmcZw6M --manifest verification_manifest.csv
python3 transcribe_and_align.py --video gO2l7pMrMvo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video IWEqIFEPqaU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video VhlEB-HCM2g --manifest verification_manifest.csv
python3 transcribe_and_align.py --video TtbW3UcI9RU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video utCuLwh1PZ4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video TxIRZe-xi8I --manifest verification_manifest.csv
python3 transcribe_and_align.py --video jSuMCrvbwDo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video lhfNq6N2-C0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ieq-9RNUO-Y --manifest verification_manifest.csv
python3 transcribe_and_align.py --video poNk9wEJ-Ds --manifest verification_manifest.csv
python3 transcribe_and_align.py --video xEtlmaIOPvE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video tZoCtvvTxFY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video L6Y6aBYT7LA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video CXGqUvp-1dM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video qAcWR9yFwPQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 54_VPYHdoHc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video _zbnDMJvHfE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video r6a-p9RVaHQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video o5PdIgc_xo4 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 1Ih8DJu4mXs --manifest verification_manifest.csv
python3 transcribe_and_align.py --video K4YptPZ8Vpc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video qnO1WlhoDgk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Sdujv1OdYb8 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video hqrDHaYNuDU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 7bKK7ry0nqk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 7_Q5-2c-OZQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video XJ52IYru5Ao --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 8wT7tU_Vt2w --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 8cozlcHy2FQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video G8XTrx07_wE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video qNgBuJkq4ls --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DyAonGvKuWA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video XqMYK7lxGEw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video RoilyW_gtZM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 3Vv1n-MUyxE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video oll-NwegLog --manifest verification_manifest.csv
python3 transcribe_and_align.py --video soDyICEdnGE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video m5xrYOx8Scw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video _XGCy0rxKf0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video egxRSxk2c1w --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 82jxuERn5Zw --manifest verification_manifest.csv
python3 transcribe_and_align.py --video jiKvNIfWprk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video q_U_dj9d91s --manifest verification_manifest.csv
python3 transcribe_and_align.py --video s_jal2MF1FU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 1BFYpT9bRHA --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 83XioPf4h4w --manifest verification_manifest.csv
python3 transcribe_and_align.py --video vC_E22tyavI --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DfZYbZrqNNU --manifest verification_manifest.csv
python3 transcribe_and_align.py --video uBVmjl9CxIY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video PJgpyn0LCTo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video PU1W2YgmL4M --manifest verification_manifest.csv
python3 transcribe_and_align.py --video cpXTxH-V2hY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video upbgvCHYYoc --manifest verification_manifest.csv
python3 transcribe_and_align.py --video 4JLdqGp9W_A --manifest verification_manifest.csv
python3 transcribe_and_align.py --video lyxR3efjiVE --manifest verification_manifest.csv
python3 transcribe_and_align.py --video gKSUR7nw6FQ --manifest verification_manifest.csv
python3 transcribe_and_align.py --video Ody4amuX03Q --manifest verification_manifest.csv
python3 transcribe_and_align.py --video JslUppYGYzo --manifest verification_manifest.csv
python3 transcribe_and_align.py --video cZdxDladl-Y --manifest verification_manifest.csv
python3 transcribe_and_align.py --video XDXZbHAGk80 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video BBDLz38VzFM --manifest verification_manifest.csv
python3 transcribe_and_align.py --video CdcT1SwLS1U --manifest verification_manifest.csv
python3 transcribe_and_align.py --video xeV8JElIUqk --manifest verification_manifest.csv
python3 transcribe_and_align.py --video sGlPJrMU070 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video ClkTYzvmn84 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video loQ6ZgJ0_Io --manifest verification_manifest.csv
python3 transcribe_and_align.py --video RtM4bKZU7E0 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video xl3nNuXyBxg --manifest verification_manifest.csv
python3 transcribe_and_align.py --video zcRhBCkvu20 --manifest verification_manifest.csv
python3 transcribe_and_align.py --video DdCRnWqQLpY --manifest verification_manifest.csv
python3 transcribe_and_align.py --video tsOJAjZJUnI --manifest verification_manifest.csv